language: python
python:
- 2.7

install:
- pip install sphinx sphinx-autobuild
- pip install recommonmark

script:
- make html

deploy:
- provider: s3
  access_key_id: AKIAJ5AUBLQFMZ62ZDUA
  secret_access_key:
    secure: "e5xxPB7Ez8gGnx4s9a0JQU+5LbP7Xd684aDII22QyjzRF5N0tTbTzeFZu6zkIY+me/dQQb6jHSUQmAqT2WpacuU1smC29mgYAzX+6Jt09UBd79h96ne0JHO/M7ghW6yhLwTa1VbEqy9Up+tRiJpZY/z5Gx0TFVxYwxqJNNgo+IT9o1NWkI/bm50MBY3UCPSLoODTS8UM88fk+Yg3tHD4WFIYDIvFgWLmUpwBuoswo6GT7eeJYHovqXHRAzomrJcvjLw/QpsjyR8twYOjA3wcqRlimfx3GUipR239HCXbtDa3lIJFBtyz57l7Av480GVJ1iSDrLSshxfO9I6ADgBvZZcgsFmZ/2TITQ7kJQ2ESIr21sfcxLsA+DK8IJ5Cw8upJ1eA1/qk1uasD2VgZs87sYxGNRwDzhtJaVuaWAVfoGZUFBMJawwzu53JZSWbv1uGCYM7MGcOls3mDJnil/pNpWqoAxojNkk4+HRYpcVUCMynnZQaPF9Z1M7pRTzAH8eWepHHxLL5HVrywJj/eU6njXHe/Ekv2xmoJ93AAbGXLEQI10KRFsV07P1DefkYcGdqazMLEpOSnRUGIz5G6GUd0Ewi4ajV56YvvxansiKc2fYT9da/EnpLSlLMq1ZdlsBIIYpAjYgIHx+cIEO7uThQFxkXMfozdWfzomi+0N2H2xs="
  bucket: docs.mattermost.org
  local_dir: "build/html"
  acl: public_read
  region: us-east-1
  skip_cleanup: true
  detect_encoding: true
  on:
    repo: mattermost/docs
    branch: master
    python: 2.7