language: python
python:
- 2.7
install:
- pip install sphinx sphinx-autobuild
- pip install recommonmark
script:
- make html

deploy:
- provider: s3
  access_key_id: AKIAJ5AUBLQFMZ62ZDUA
  secret_access_key: 
       secure: "OD3JfbWtDY+10oBUM9jeq2yZb+Dvr/XGSs4R/Ej1wT3XRYjiizRBCsteaRlTi79sXsZlayCsaTodkxgnNt204O+UQTmXDvRoSBV5iLxepztOrZgwpiU1ejjTDV5MJapmubsxRIOT/gpQ0in1QWReQ/2OXWJYJ3tZppGzwiGxeh3HSoqKBtFdjDCaTF8kpMCKvDag8U5FZKrclCRewuTxTjlpPrZbPruCL95FaVCB9HCENksnwSx+zjXP+6r4PfGK/0kJmlk1bhAqFY9D36o/uXMCpFnwHacXpYln7tca7qdYh7UQufkd04hd1kHXQyiUeaFrh5ccZp307wiS5Jw5KrfB96rcrUypd4SJUXiCs76x3dJWOu1I7yiuRaRuUKLLpj1RVIUIUDB0ZQczFsjNOwJpdxCBcMpxA2UDwqni5XfviLKHv6L0a+enxSztFihdkkywEaWGBNRPdafvJu4X0iOWqzA5kjwo9R46uvq7lSb1o5qtsK2PpKd55DOl/V6lDLrq/r/yQXv5yZaiy0kb2ZBQh4xeguIFb6U6cvqyGkeDnQ+mdVUSvJZ9rj+cOF0ooeq0B8X8Oi7AEh8OAHLuyiPV6TNoxGjVS8rHH4FZbPTDXnlgmF1qb6qCfmlHDz2Bojx69lWLF1P55XtwhcD4mBRTsmMcyAe5rR+hzpU+AuY="
  bucket: docs.mattermost.org
  local_dir: "build/html"
  acl: public_read
  region: us-east-1
  skip_cleanup: true
  detect_encoding: true
  on:
    repo: mattermost/docs
    branch: master
    python: 2.7