language: python
python:
- 2.7

install:
- pip install sphinx sphinx-autobuild
- pip install recommonmark

script:
- make html

deploy:
- provider: s3
  access_key_id: AKIAJXLDG4C2F4MIZP4Q
  secret_access_key:
    secure: "CodRbmeh0igFRN7Yban8RmLVcpMiu+zZlMANYhCbt7riKG8Cn0KjVj+2UMA/eJ5RDFVRwOUo6L93fnwZl7HI1e7IbX0CNbIUOyLmuFkvCgxJ3rwLaB6J+FThBcCE8y8PQj4cdFUzKNczcDKEs4MxgIclIlyBN+moIFvtz4VUseGglgzD8u/ExSZIUM0tRDZKDhMwL45P5OoFIFC+Rq5BnJVAD9mfXvY4t7XvxO/bhdnsgBpgW4u5goog4dzAXhhT0EU+477GxxszJ7MXW7g9vhDdlBwb9UrbW5zaS0hTQeq9VOiCgwVRCx1PaycsnRFdzbGJmJk4zyl9YECzusewi/mDJMqpa/Q+BprLCtgGcAQrxBChDKY4GC0aVKwYSX3uiyE56GpZcBgEp+PjAZNDzYWpRHEMZANVgJkBAR6AobUoUunkVG+N2MUXrDRwj0WpA0kcRF6Ln6aQ3zNLU0i3rhzPBTstySIKDG0dW1vrLBix1dYixAxJtUBBsaszjIjc4w/wCknU2MKSaGEmI5gdQgCane0UTpVLFYisBAYCRz6t3DJvdBzLiH8L9vxmgS94Kzb0e6Hs4TBucAD4kN+cXt7OZc7rdphIwv39QGuYmE/gbTKGYwlB6XC0pfBddJ3/2mxNutUGj/PPjw5ubrU5stFaFeogaqiBT2TY+nKIO/M="
  bucket: docs.mattermost.org
  local_dir: "build/html"
  acl: public_read
  region: us-east-1
  skip_cleanup: true
  detect_encoding: true
  on:
    repo: mattermost/docs
    branch: master
    python: 2.7